I plan to explore the following questions:
The general theme is, which streets are likely to be less crowded in Seattle
1) Which street has the highest recorded traffic
2) Which street has the lowest recorded traffic
3 & 4) Do downtown streets or non-downtown streets have a higher average traffic level
5) Which downtown street had the lowest traffic in the most recent year.

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import os

In [8]:
data = pd.read_csv(os.getcwd() + '/Traffic_Flow_Counts.csv', delimiter=",",
                   names = ['downtown', 'stname', 'year', 'aawdt'])
data

    downtown                         stname  year   aawdt
0      False                      N 45TH ST  2009   22200
1      False                     NE 80TH ST  2009    9500
2       True                      DENNY WAY  2009   30200
3      False                     E ALOHA ST  2009    7600
4      False                     51ST AVE S  2009    6300
5      False                    24TH AVE NW  2009   10300
6      False                     10TH AVE E  2009   13100
7      False               NE NORTHGATE WAY  2009   29500
8       True                       JAMES ST  2009   33400
9      False                     NW 80TH ST  2009    8500
10     False                   AURORA AVE N  2009   36700
11     False                      4TH AVE S  2009   23800
12     False                  AIRPORT WAY S  2009   16700
13     False                     15TH AVE W  2009   38500
14     False                    S LUCILE ST  2009    6800
15      True                      DENNY WAY  2009   24000
16     False                   E YESLER WAY  2009    8000
17      True                      BOREN AVE  2009   21300
18     False                DELRIDGE WAY SW  2009   13400
19     False              FAUNTLEROY WAY SW  2009   16500
20     False               QUEEN ANNE AVE N  2009   12200
21     False                       14TH AVE  2009    8100
22     False                     NE 75TH ST  2009   16700
23      True                        7TH AVE  2009    7300
24     False                     NE 45TH ST  2009   36900
25     False                      N 46TH ST  2009   24500
26     False                      N 65TH ST  2009    7900
27     False                   SW MORGAN ST  2009    7400
28     False                    E CHERRY ST  2009    8000
29     False                   S GENESEE ST  2009    9800
..       ...                            ...   ...     ...
782    False              SPRING ST ON RAMP  2007   16100
783    False              UNION ST OFF RAMP  2007    9800
784    False            JAMES ST ON RAMP SB  2007   20800
785    False           CHERRY ST ON RAMP NB  2007   12400
786    False            MADISON ST OFF RAMP  2007   13400
787    False             CHERRY ST REV RAMP  2007    3900
788     True                    WESTERN AVE  2007    7600
789     True                    ALASKAN WAY  2007   14300
790    False                        SR99 FY  2007   39700
791    False                       SR509 NB  2007   58700
792    False          ALASKAN WY VI NB & SB  2007   54700
793    False          ALASKAN WY VI NB & SB  2007   86200
794    False        WEST SEATTLE BR EB & WB  2007   66400
795    False        WEST SEATTLE BR EB & WB  2007   85100
796    False        WEST SEATTLE BR EB & WB  2007   44300
797    False                    35TH AVE SW  2007   23300
798    False      BATTERY ST TUNNEL NB & SB  2007   66400
799    False          ALASKAN WY VI NB & SB  2007  110100
800    False              M L KING JR WAY S  2007   16800
801    False              M L KING JR WAY S  2007   19900
802    False                 S HENDERSON ST  2007    6800
803    False                    S GRAHAM ST  2007   11300
804    False                  RAINIER AVE S  2007   34700
805    False                   S JACKSON ST  2007   14600
806    False      ML KING JR BLVD S NB & SB  2007   14800
807    False      M L KING JR WAY S NB & SB  2007   18700
808    False                S COLUMBIAN WAY  2007   39600
809    False  NORTHGATE WAY W/O 15TH AVE NE  2007   18000
810    False               ROOSEVELT WAY NE  2007   12400
811     True            MELROSE AVE ON RAMP  2007   16000

[812 rows x 4 columns]

Cleaning any incomplete data:

In [39]:
data = data.fillna(data.mode())

In [38]:
print("Highest recorded traffic")
print(data[data.aawdt == data.aawdt.max()].stname)

Highest recorded traffic
258    ALASKAN WY VI NB & SB
Name: stname, dtype: object

In [12]:
print("Lowest recorded traffic")
print(data[data.aawdt == data.aawdt.min()].stname)

Lowest recorded traffic
726    8TH AVE S
Name: stname, dtype: object

In [25]:
print("average downtown traffic rating")
print(sum(data[data.downtown == True].aawdt / len(data[data.downtown == True])))

average downtown traffic
15061.6857143

In [26]:
print("average non-downtown traffic rating")
print(sum(data[data.downtown == False].aawdt / len(data[data.downtown == False])))

average non-downtown traffic rating
20396.0339463

In [36]:
print("Lowest recorded downtown traffic")
dataset = data[(data.downtown == True) & (data.year == data.year.max())]
print(dataset[dataset.aawdt == dataset.aawdt.min()].stname)

Lowest recorded downtown traffic
138    8TH AVE
Name: stname, dtype: object